config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create]
  end


  # get 'restaurants', to: 'restaurants#index'

  # get 'restaurants/new', to: 'restaurants#new'

  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurants

  # get 'restaurants/:id/review', to: 'restaurants#review', as: :review_restaurants

  # patch 'restaurants/:id', to: 'restaurants#update'

  # # post 'restaurants', to: 'restaurants#create'

  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # # get 'reviews', to: 'reviews#index'

  # delete 'restaurants/:id', to: 'restaurants#destroy'
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5 }
  validates :rating, numericality: { only_integer: true }
end


# A review must belong to a restaurant.
# A review must have a content.
# A review must have a rating.
# A review’s rating must be a number between 0 and 5.
# A review’s rating must be an integer. For example, a review with a rating of 2.5 should be invalid!

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # def create
  #   @restaurant = Restaurant.new(restaurant_params)
  #   @restaurant.save

  #   redirect_to restaurant_path(@restaurant)
  # end


  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul> <h1> Restaurants</h1>
  <% @restaurants.each do |restaurant| %>
    <li> <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%# <%= link_to "Delete", restaurant_path(restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%> </li>

    <% end %>
</ul>

<%# <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<ul class="list-unstyled">
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.rating %> ⭐️ - <%= review.content %></li>
  <% end %>
</ul>


<%# <p><%= @restaurant.rating %></

    <%# <%= button_to "Edit", edit_restaurants_path, method: :get, class: "btn btn-primary" %> %>
    <%= link_to "Reviews", new_restaurant_review_path(@restaurant, @review), class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>